on:
  pull_request:
    branches:
      - "staging"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./garden
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install    
      - name: Test
        run: npm test
        env:
          CI: true
      # We don't do anything with the build but this makes sure we can at least build it
      - name: Generate build
        run: npm run build