on:
  push:
    branches:
      - "main"
      - "prod"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./garden
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install    
      - name: Generate build
        run: npm run predeploy
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: react-github-actions-build
          path: ./garden/build
      
  prod-deploy:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: react-github-actions-build    
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: react-github-actions-build
          commit_message: ${{ github.event.head_commit.message }}

  staging-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: react-github-actions-build
          path: build   
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: Garden-AI/garden-frontend-staging
          deploy_key: ${{ secrets.STAGING_DEPLOY_KEY }}
          publish_dir: build
          commit_message: ${{ github.event.head_commit.message }}