on:
  push:
    branches:
      - "staging"
      - "prod"

jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - name: Get branch name
          id: branch-name
          uses: tj-actions/branch-names@v6
        - name: Clone repository
          uses: actions/checkout@v3
        - name: Use Node.js 18.x
          uses: actions/setup-node@v3
          with:
            node-version: 18.x
        - name: Install dependencies
          run: npm install    
        - name: Generate build
          run: npm run predeploy
        - name: Generate build
          run: npm run deploy-${{ steps.branch-name.outputs.current_branch }}"